[package]
description = "Standard library for Desmos with CosmWasm support included"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "desmos-std"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4.24", default-features = false}
cosmwasm-std = {version = "1.2.5", features = ["stargate", "backtraces"]}
std-derive = {version = "0.1.0", path = "../std-derive"}
prost = {version = "0.11.0", default-features = false, features = ["prost-derive"]}
prost-types = {version = "0.11.9", default-features = false}
schemars = "0.8.11"
serde = {version = "1.0.163", default-features = false, features = ["derive"]}
serde-cw-value = "0.7.0"
mock = { version = "0.1.0", path = "../mock" }
base64 = "0.21.0"
strum_macros = "0.24.3"
