mod msg;
mod query;

use desmos_bindings::subspaces::types::Subspace;

/// Returns the denom generated by the given subspace.
pub fn get_denom(subspace: &Subspace, subdenom: &str) -> String {
    format!("factory/{}/{}", subspace.treasury, subdenom)
}
