[package]
name = "desmos-bindings"
version = "1.2.1"
authors = [
    "Leonardo Bragagnolo <leonardo@forbole.com>",
    "Paul Chen <paul@forbole.com>",
    "Manuel Turetta <manuel@forbole.com>",
]
edition = "2021"
description = "CosmWasm bindings to custom Desmos features"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-bindings"
homepage = "https://www.desmos.network"
keywords = ["social-networks", "blockchain", "smart-contracts", "desmos", "cryptocurrency"]
readme = "../../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
chrono = {version = "0.4.22", default-features = false}
cosmwasm-std = { version = "1.2.1", features = ["stargate"]}
cosmwasm-schema = "1.2.1"
anyhow = "1.0.69"
serde = { version = "1.0.155", default-features = false, features = ["derive"] }
thiserror = "1.0.39"
std-derive = { version = "0.1.0", path = "../std-derive" }
prost = {version = "0.11.0", default-features = false, features = ["prost-derive"]}
prost-types = {version = "0.11.1", default-features = false}
serde-cw-value = "0.7.0"
desmos-std = { version = "0.1.0", path = "../std" }
mock = { version = "0.1.0", path = "../mock" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { version = "0.16.2" }

[features]
default = ["profiles", "subspaces", "posts", "relationships", "reports", "reactions"]
profiles = []
subspaces = []
posts = []
relationships = []
reports = []
reactions = []
iterators = []
