[package]
name = "desmos-bindings"
version = "1.0.0"
authors = [
    "Leonardo Bragagnolo <leonardo@forbole.com>",
    "Paul Chen <paul@forbole.com>",
    "Manuel Turetta <manuel@forbole.com>",
]
edition = "2018"
description = "CosmWasm bindings to custom Desmos features"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-bindings"
homepage = "https://www.desmos.network"
keywords = ["social-networks", "blockchain", "smart-contracts", "desmos", "cryptocurrency"]

[dependencies]
anyhow = "1.0.58"
cosmwasm-std = { version = "1.0.0" }
cw-multi-test = { version = "0.13.4", optional = true }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.31"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }

[features]
default = ["profiles", "subspaces", "posts", "relationships", "reports", "reactions", "query", "msg"]
profiles = []
subspaces = []
posts = []
relationships = []
reports = []
reactions = []
query = []
msg = []
mocks = ["query", "dep:cw-multi-test"]
iterators = []
