[package]
name = "desmos-bindings"
version = "1.2.0"
authors = [
    "Leonardo Bragagnolo <leonardo@forbole.com>",
    "Paul Chen <paul@forbole.com>",
    "Manuel Turetta <manuel@forbole.com>",
]
edition = "2018"
description = "CosmWasm bindings to custom Desmos features"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-bindings"
homepage = "https://www.desmos.network"
keywords = ["social-networks", "blockchain", "smart-contracts", "desmos", "cryptocurrency"]
readme = "../../README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
anyhow = "1.0.66"
cosmwasm-std = { version = "1.1.5" }
schemars = "0.8.11"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
thiserror = "1.0.37"
cosmwasm-schema = { version = "1.1.6" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { version = "0.16.1"}

[features]
default = ["profiles", "subspaces", "posts", "relationships", "reports", "reactions", "query", "msg"]
profiles = []
subspaces = []
posts = []
relationships = []
reports = []
reactions = []
query = []
msg = []
iterators = []
mocks = ["query", "msg"]
