[package]
name = "desmos-bindings"
version = "2.0.1"
authors = [
    "Leonardo Bragagnolo <leonardo@forbole.com>",
    "Paul Chen <paul@forbole.com>",
    "Manuel Turetta <manuel@forbole.com>",
]
edition = "2021"
description = "CosmWasm bindings to custom Desmos features"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-bindings"
homepage = "https://www.desmos.network"
keywords = ["social-networks", "blockchain", "smart-contracts", "desmos", "cryptocurrency"]
readme = "../../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
chrono = {version = "0.4.26", default-features = false}
cosmwasm-std = { version = "1.3.1", features = ["stargate"]}
cosmwasm-schema = "1.3.1"
serde = { version = "1.0.181", default-features = false, features = ["derive"] }
prost = {version = "0.11.0", default-features = false, features = ["prost-derive"]}
prost-types = {version = "0.11.9", default-features = false}
serde-cw-value = "0.7.0"
desmos-mock = { version = "2.0.1", path = "../mock" }
schemars = "0.8.11"
strum_macros = "0.25.2"
base64 = "0.21.2"
desmos-std-derive = {version = "2.0.1", path = "../std-derive"}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { version = "0.16.5" }

[features]
default = ["profiles", "subspaces", "posts", "relationships", "reports", "reactions"]
profiles = []
subspaces = []
posts = []
relationships = []
reports = []
reactions = []
iterators = []
backtraces = ["cosmwasm-std/backtraces", "desmos-std-derive/backtraces"]
