[package]
name = "desmos-bindings"
version = "1.2.1"
authors = [
    "Leonardo Bragagnolo <leonardo@forbole.com>",
    "Paul Chen <paul@forbole.com>",
    "Manuel Turetta <manuel@forbole.com>",
]
edition = "2018"
description = "CosmWasm bindings to custom Desmos features"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-bindings"
homepage = "https://www.desmos.network"
keywords = ["social-networks", "blockchain", "smart-contracts", "desmos", "cryptocurrency"]
readme = "../../README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
cosmwasm-std = "1.2.1"
cosmwasm-schema = "1.2.1"
anyhow = "1.0.69"
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
thiserror = "1.0.39"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { version = "0.16.2" }

[features]
default = ["profiles", "subspaces", "posts", "relationships", "reports", "reactions"]
profiles = []
subspaces = []
posts = []
relationships = []
reports = []
reactions = []
iterators = []
