[package]
name = "desmos-bindings"
version = "3.0.0"
authors = [
    "Leonardo Bragagnolo <leonardo@forbole.com>",
    "Paul Chen <paul@forbole.com>",
    "Manuel Turetta <manuel@forbole.com>",
]
edition = "2021"
description = "CosmWasm bindings to custom Desmos features"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-bindings"
homepage = "https://www.desmos.network"
keywords = ["social-networks", "blockchain", "smart-contracts", "desmos", "cryptocurrency"]
readme = "../../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
chrono = {version = "0.4.31", default-features = false}
cosmwasm-std = { version = "1.5.0", features = ["stargate"]}
cosmwasm-schema = "1.5.0"
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
prost = {version = "0.12.3", default-features = false, features = ["prost-derive"]}
prost-types = {version = "0.12.3", default-features = false}
serde-cw-value = "0.7.0"
desmos-mock = { version = "3.0.0", path = "../mock" }
schemars = "0.8.16"
strum_macros = "0.25.3"
base64 = "0.21.5"
desmos-std-derive = {version = "3.0.0", path = "../std-derive"}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { version = "0.20.0" }

[features]
default = ["profiles", "subspaces", "posts", "relationships", "reports", "reactions", "tokenfactory"]
profiles = []
subspaces = []
posts = []
relationships = []
reports = []
reactions = []
tokenfactory = []
iterators = []
# TODO: Enable backtraces feature when it becomes stable feature
# backtraces = ["cosmwasm-std/backtraces"]
