[package]
edition = "2021"
name = "proto-build"
version = "0.1.0"
publish = false

[dependencies]
heck = "0.5.0"
itertools = "0.12.1"
log = "0.4.21"
pretty_env_logger = "0.5.0"
prettyplease = "0.2.20"
prost = "0.12.3"
prost-build = "0.12.3"
prost-types = "0.12.3"
quote = "1.0.33"
regex = "1"
syn = {version = "2.0.52", features = ["full", "parsing", "extra-traits"]}
walkdir = "2"
proc-macro2 = "1.0.82"
