[package]
edition = "2021"
name = "proto-build"
publish = false
version = "0.1.0"

[dependencies]
heck = "0.4.0"
itertools = "0.10.5"
log = "0.4.17"
pretty_env_logger = "0.4.0"
prettyplease = "0.1.25"
prost = "0.11.0"
prost-build = "0.11.1"
prost-types = "0.11.1"
regex = "1"
syn = {version = "1.0.103", features = ["full", "parsing", "extra-traits"]}
tonic = "0.9.2"
walkdir = "2"
