[package]
edition = "2021"
name = "proto-build"
publish = false
version = "0.1.0"

[dependencies]
heck = "0.4.0"
itertools = "0.10.3"
log = "0.4.17"
pretty_env_logger = "0.4.0"
prettyplease = "0.1.16"
prost = "0.10"
prost-build = "0.10"
prost-types = "0.10"
regex = "1"
syn = {version = "1.0.98", features = ["full", "parsing", "extra-traits"]}
tonic = "0.7"
tonic-build = "0.7"
walkdir = "2"
proc-macro2 = "1.0.18"