[package]
edition = "2021"
name = "proto-build"
version = "0.1.0"
publish = false

[dependencies]
heck = "0.4.0"
itertools = "0.11.0"
log = "0.4.19"
pretty_env_logger = "0.5.0"
prettyplease = "0.2.10"
prost = "0.11.0"
prost-build = "0.11.9"
prost-types = "0.11.9"
quote = "1.0.29"
regex = "1"
syn = {version = "2.0.26", features = ["full", "parsing", "extra-traits"]}
walkdir = "2"
proc-macro2 = "1.0.66"
