[package]
description = "Mock helpler for testing"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "desmos-mock"
version = "3.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = {version = "1.5.4", features = ["stargate"]}

