[package]
description = "Procedural macro for desmos-std"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "desmos-std-derive"
version = "3.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
itertools = "0.12.1"
proc-macro2 = "1.0.78"
quote = "1.0.33"
syn = "2.0.50"

[dev-dependencies]
cosmwasm-std = {version = "1.5.2", features = ["stargate"]}
prost = "0.12"
serde = "1.0.196"
trybuild = {version = "1.0.89", features = ["diff"]}
desmos-mock = { version = "3.0.0", path = "../mock" }
