[package]
description = "Procedural macro for desmos-std"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "desmos-std-derive"
version = "2.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
itertools = "0.11.0"
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.38"

[dev-dependencies]
cosmwasm-std = {version = "1.4.0", features = ["stargate"]}
prost = "0.12"
serde = "1.0.189"
trybuild = {version = "1.0.85", features = ["diff"]}
desmos-mock = { version = "2.0.1", path = "../mock" }
