[package]
description = "Procedural macro for desmos-std"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "desmos-std-derive"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.3"
proc-macro2 = "1.0.58"
quote = "1.0.27"
syn = "2.0.16"

[dev-dependencies]
cosmwasm-std = {version = "1.2.6", features = ["stargate"]}
prost = "0.11"
serde = "1.0.163"
trybuild = {version = "1.0.80", features = ["diff"]}
desmos-mock = { version = "0.1.0", path = "../mock" }
