[package]
description = "Procedural macro for desmos-std"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "desmos-std-derive"
version = "2.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backtraces = ["cosmwasm-std/backtraces"]

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.3"
proc-macro2 = "1.0.60"
quote = "1.0.29"
syn = "2.0.23"

[dev-dependencies]
cosmwasm-std = {version = "1.2.7", features = ["stargate"]}
prost = "0.11"
serde = "1.0.163"
trybuild = {version = "1.0.80", features = ["diff"]}
desmos-mock = { version = "2.0.1", path = "../mock" }
